### PR TITLE
Implemented sharing functionality, as well as Chrome Custom Tabs!

### PR DESCRIPTION
**Pull request by evieluvsrainbows**
I have implemented sharing functionality in the app, as well as swapped over from using the normal WebViews to Chrome Custom Tabs, which work quite a bit better than just the standard WebView that's in the normal Android API. I also did some minor reorganization of the codebase, in order to properly sort classes instead of bundling them all into one big folder.

One more thing: I switched from the normal Android logging system to Timber, which doesn't require a tag. I had to create a class based on android.app.Application in order to plant the Debug Tree, but I'm pretty sure that's fine, and I restricted it to debug builds as well in order to prevent logging in release builds, to prevent cluttering up Android Logcat.

### CODE REVIEW

**Comment by brian-norman** [comment]
Hey interesting PR, thanks! We're curious about who you are and why are you making changes though?

**Comment by evieluvsrainbows** [comment]
@brian-norman Oh, that's fair! I discovered the project via the Explore page of GitHub, trying to find interesting projects to contribute to! This one happened to be really new and I decided to help out a bit 🙂 I really hope that's okay!

**Comment by brian-norman** [comment]
Since we have that bottom space not being used much under the articles now (because of the menu icon) can we just turn that menu icon to [share icon](https://material.io/tools/icons/?icon=share&style=baseline) and just have it be a share button? 

Any future icons can be added beside it instead of being hidden behind another click!

**Review by brian-norman — APPROVED** [review]
LGTM thanks!

**Pull request merged**
